language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan master
    git rm -rf .
    mv public/* .
    rm -rf public hugo_*
    git add -f --ignore-errors --all
    git -c user.name='dheerendramehar' -c user.email='dheerenm95@gmail.com' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/dheerendramehar/dheerendramehar.github.io master
    fi
