
language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    - rm -rf publc || exit 0

# Build the website
script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  on:
    branch: master  # branch contains Hugo generator code

